name: Docker Build and Push on Release
on:
  release:
    types: [published, edited]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Release Version
        id: get_version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)" >> $GITHUB_OUTPUT
          echo "MINOR_VERSION=$(echo $VERSION | cut -d. -f1-2)" >> $GITHUB_OUTPUT
          
      - name: Echo Version
        run: |
          echo ${{ steps.get_version.outputs.RELEASE_VERSION }}
          echo ${{ steps.get_version.outputs.MAJOR_VERSION }}
          echo ${{ steps.get_version.outputs.MINOR_VERSION }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKER_USERNAME }}/personal_ubuntu_conf:latest
      #       ${{ secrets.DOCKER_USERNAME }}/personal_ubuntu_conf:${{ steps.get_version.outputs.RELEASE_VERSION }}
      #       ${{ secrets.DOCKER_USERNAME }}/personal_ubuntu_conf:${{ steps.get_version.outputs.MAJOR_VERSION }}
      #       ${{ secrets.DOCKER_USERNAME }}/personal_ubuntu_conf:${{ steps.get_version.outputs.MINOR_VERSION }}